on 403, more info
oda-hub/dispatcher-plugin-integral pull request #36
Opened 2021-05-21 12:01 UTC by volodymyrss

2021-05-21 12:04 UTC, volodymyrss commented
test to be adapted once dispacher-app interface merges

2021-05-21 12:07 UTC, burnout87 requested changes

2021-05-21 12:07 UTC, burnout87 commented on cdci_osa_plugin/osa_dataserve_dispatcher.py
> +        needed_roles_with_comments = {}
I guess this will have to be returned, along with needed_roles

2021-05-21 12:09 UTC, volodymyrss commented
until no test it's draft

2021-05-27 18:29 UTC, volodymyrss commented
combined with #37 which is similar

2021-05-31 07:23 UTC, closed without merging