init OSAVersion
oda-hub/dispatcher-plugin-integral pull request #63
Opened 2021-10-04 13:18 UTC by burnout87

Initialized as a Name parameter

2021-10-04 13:18 UTC, pep8speaks commented
Hello @burnout87! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`cdci_osa_plugin/osa_common_pars.py`](https://github.com/oda-hub/dispatcher-plugin-integral/blob/11bbbbc7b6ea36a6bc9ccce0ac7c2fa73281e6fd/cdci_osa_plugin/osa_common_pars.py):

> [Line 94:66](https://github.com/oda-hub/dispatcher-plugin-integral/blob/11bbbbc7b6ea36a6bc9ccce0ac7c2fa73281e6fd/cdci_osa_plugin/osa_common_pars.py#L94): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 94:67](https://github.com/oda-hub/dispatcher-plugin-integral/blob/11bbbbc7b6ea36a6bc9ccce0ac7c2fa73281e6fd/cdci_osa_plugin/osa_common_pars.py#L94): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 96:80](https://github.com/oda-hub/dispatcher-plugin-integral/blob/11bbbbc7b6ea36a6bc9ccce0ac7c2fa73281e6fd/cdci_osa_plugin/osa_common_pars.py#L96): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 122:80](https://github.com/oda-hub/dispatcher-plugin-integral/blob/11bbbbc7b6ea36a6bc9ccce0ac7c2fa73281e6fd/cdci_osa_plugin/osa_common_pars.py#L122): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)

2021-10-04 13:54 UTC, burnout87 commented
This only tackles the initialization of a OSAVersion parameter. An additional change would ideally be required at dispatcher level.

2021-10-04 14:01 UTC, volodymyrss requested changes
cannt check closely. Well it fails CI test. Coverage of this might needs to be improved.

2021-10-04 14:04 UTC, burnout87 commented on cdci_osa_plugin/osa_common_pars.py
> +        super(OSAVersion, self).__init__(value=value, name=name, allowed_values=allowed_values)
Thanks for the tip!

2021-10-04 16:19 UTC, burnout87 commented
> This only tackles the initialization of a OSAVersion parameter. An additional change would ideally be required at dispatcher level.

Just noticed that also for the time parameters (eg T and T2) units is not set, and it looks like it should be the related format, also this, should be tacked at a dispatcher-app level.

2021-10-05 06:24 UTC, volodymyrss commented on cdci_osa_plugin/osa_common_pars.py
> +        super().__init__(value=value, name=name,)
extra coma at the end

2021-10-05 08:58 UTC, volodymyrss commented
the tests for ISGRI and JEMX are almost identical. Could they be combined with parametrization?

2021-10-05 09:06 UTC, burnout87 commented
> the tests for ISGRI and JEMX are almost identical. Could they be combined with parametrization?

I thought the same, but I went for this approach since we already had two instrument specific test modules.

2021-10-05 09:13 UTC, volodymyrss commented
> > the tests for ISGRI and JEMX are almost identical. Could they be combined with parametrization?
> 
> I thought the same, but I went for this approach since we already had two instrument specific test modules.

We also have test groups not specific to instruments.

Why further increase duplication, even if there is some already. For whatever reason it was done before. It's easier to maintain code without duplication, in case of changes it's not necessary to duplicate them too.

I do not suppose it's any more difficult to do it in two tests instead of four?
Well, if it's not convenient now, we can leave a note and do it later.

2021-10-05 09:45 UTC, burnout87 commented
> > > the tests for ISGRI and JEMX are almost identical. Could they be combined with parametrization?
> > 
> > 
> > I thought the same, but I went for this approach since we already had two instrument specific test modules.
> 
> We also have test groups not specific to instruments.
> 
> Why further increase duplication, even if there is some already. For whatever reason it was done before. It's easier to maintain code without duplication, in case of changes it's not necessary to duplicate them too.
> 
> I do not suppose it's any more difficult to do it in two tests instead of four? Well, if it's not convenient now, we can leave a note and do it later.

and now they are

2021-10-05 09:46 UTC, volodymyrss approved these changes
cool, thanks!

2021-10-05 09:49 UTC, merged